
project_id = "cxcdfurwsefllhxucjnz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
external_email_enabled = true
external_phone_enabled = true
external_sms_enabled = true
external_anonymous_users_enabled = false
external_url = "http://localhost:54321"

# Public endpoints that need to be accessible without authentication
[functions.ai-assistant]
verify_jwt = false

[functions.contact-consultation]
verify_jwt = false

[functions.tally-webhook]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

# Protected endpoints that require authentication
[functions.create-payment]
verify_jwt = true

[functions.gmail-support]
verify_jwt = true

[functions.analytics]
verify_jwt = true

# Test/debug endpoints - disable in production
[functions.whatsapp-test]
verify_jwt = true

[functions.debug-env]
verify_jwt = true

[functions.twilio-test]
verify_jwt = true

# Webhook handlers with their own validation
[functions.whatsapp-handler]
verify_jwt = false
